name: deploy

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up GraalVM
        uses: graalvm/setup-graalvm@v1
        with:
          java-version: '17'
          distribution: 'graalvm-community'
          cache: maven

      - name: Build with Project
        run: |
          bash ./package.sh

          time=$(date +%s%3N)
          version=$(cat ani-rss-application/pom.xml | grep -oPm1 '(?<=<version>).*?(?=</version>)')
          echo "{\"time\":$time,\"version\":\"$version\"}" > info.json
          jq --arg content "$(cat UPDATE.md)" '. += {markdown: $content}' info.json > temp.json && mv temp.json info.json

          echo "$(cat info.json)"
          echo "version=v$version" >> $GITHUB_ENV

      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          name: ${{ env.version }}
          body_path: UPDATE.md
          tag_name: ${{ env.version }}
          append_body: false
          token: ${{ secrets.GITHUB_TOKEN }}
          files: |
            ./ani-rss-application/target/ani-rss.jar
            ./ani-rss-application/target/ani-rss.jar.md5
            ./ani-rss-application/target/ani-rss.exe
            ./ani-rss-application/target/ani-rss.exe.md5
            ./ani-rss-application/target/ani-rss-application
            ./ani-rss-application/target/lib*.so
            ./info.json

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image (native)
        uses: docker/build-push-action@v6
        with:
          context: ./
          file: ./docker/Dockerfile
          platforms: linux/amd64
          push: true
          tags: izumiko/ani-rss:latest-native,izumiko/ani-rss:${{ env.version }}-native